# Generated by Django 3.0.3 on 2020-03-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200304_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Select a genre for this book fffff', to='catalog.Genre', verbose_name='tarek geere'),
        ),
    ]
